# Generated by Django 3.2.6 on 2021-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=200)),
                ('home_team_result', models.IntegerField()),
                ('away_team', models.CharField(max_length=200)),
                ('away_team_result', models.IntegerField()),
                ('kickof', models.DateTimeField(verbose_name='started from')),
            ],
        ),
    ]
