# Generated by Django 3.2.6 on 2021-10-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(choices=[('liverpool', 'LIVERPOOL'), ('chelsea', 'CHELSEA'), ('manu', 'MANU'), ('mancity', 'MANCITY'), ('arsenal', 'ARSENAL'), ('spurs', 'SPURS'), ('leicester', 'LEICESTER'), ('wolves', 'WOLVES'), ('southmpton', 'SOUTHAMPTON'), ('watford', 'WATFORD'), ('leeds', 'LEEDS'), ('bha', 'BHA'), ('everton', 'EVERTON'), ('astonvilla', 'ASTONVILLA'), ('brentford', 'BRENTFORD'), ('westham', 'WESTHAM'), ('crystalpalace', 'CRYSTALPALACE'), ('burnley', 'BURNLEY'), ('newcastle', 'NEWCASTLE'), ('norwich', 'NORWICH')], default='liverpool', max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(choices=[('liverpool', 'LIVERPOOL'), ('chelsea', 'CHELSEA'), ('manu', 'MANU'), ('mancity', 'MANCITY'), ('arsenal', 'ARSENAL'), ('spurs', 'SPURS'), ('leicester', 'LEICESTER'), ('wolves', 'WOLVES'), ('southmpton', 'SOUTHAMPTON'), ('watford', 'WATFORD'), ('leeds', 'LEEDS'), ('bha', 'BHA'), ('everton', 'EVERTON'), ('astonvilla', 'ASTONVILLA'), ('brentford', 'BRENTFORD'), ('westham', 'WESTHAM'), ('crystalpalace', 'CRYSTALPALACE'), ('burnley', 'BURNLEY'), ('newcastle', 'NEWCASTLE'), ('norwich', 'NORWICH')], default='liverpool', max_length=200),
        ),
    ]
