# Generated by Django 3.2.6 on 2021-10-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20211013_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='kickof',
        ),
    ]
